config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "static_pages#home"
  resources :users, only: [ :index, :new, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates :password, length: { in: 8..20 },
                       presence: true, :on => :create
  validates :email,    presence: true,
                       format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
                       uniqueness: true

  scope :admin_users, -> { where( role: 'admin' ).select( :id, :email, :role, :active ) }
  scope :sample_users, -> { where( role: 'user' ).select( :id, :email, :role, :active ) }
  scope :inactive_users, -> { where( active: false ).select( :id, :email, :role, :active ) }
  scope :all_users, -> { select( :id, :email, :role, :active ) }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UserAuthentication
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/user_authentication.rb
module UserAuthentication
  extend ActiveSupport::Concern
  
  included do 
  	helper_method :current_user 
  	helper_method :signed_in?
  	helper_method :authenticate_user!
  end

  def signed_in?
  	session[:user_id] != nil 			
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  

  def authenticate_user!
  	redirect_to log_in_path, :notice => "You need to sign in before continue" unless signed_in?
  end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]
  
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def index
    case params[:users]
    when 'admin'
      @users = User.admin_users
    when 'sample'
      @users = User.sample_users
    when 'inactive'
      @users = User.inactive_users
    when 'all'
      @users = User.all_users
    end
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pj</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<nav>
  <% if current_user %>
    Logged in as <%= current_user.email %>
    |
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %>
    |
    <%= link_to "Log in", log_in_path %>
  <% end %>
</nav>
<section>
  <div class="container">
    <div class="sidebar" id='sidebar'>
      <ul>
        <li><%= link_to 'Home', '#', id: 'home-page' %></li>
        <li><%= link_to 'All users', '#', id: 'all-users'%></li>
        <li><%= link_to 'Admin users', '#', id: 'admin-users' %></li>
        <li><%= link_to 'Sample users', '#', id: 'sample-users' %></li>
        <li><%= link_to 'Inactive users', '#', id: 'inactive-users' %></li>
      </ul>
    </div>
    <div class="content">
      <div class="main-content">
        <div id="home-content">
          <h1>Main</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum <a href="#">text link</a></p>
        </div>
        <div id="users-content">
          <h1 id="users-title"></h1>
          <ul id="users-list">
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-sidebar">Sidebar</div>
</section>

app/views/users/new.html.erb
<div class="login-page">
  <div class="form">
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for @user, class: "register-form" do |f| %>
      <%= f.text_field :email, placeholder: 'Email' %>
      <%= f.password_field(:password, placeholder: "Password") %>
      <%= f.password_field(:password_confirmation, placeholder: "Password confirmation") %>
      <%= f.submit "Log in", class: "form-button" %>
      <p class="message">Already registered? <%= link_to "Log in", log_in_path %></p>
    <% end %>
  </div>
</div>